url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Mustapha Institute" 
description: "Felling the gaps in traditional educational systems"

linkedin: mustapha-institute
github: Mustapha-Institute-Lb

collections:
  courses:
    output: true